# makefile created automaticaly by LFMakeMaker
# LFMakeMaker 2.2 (Mar 26 2000 22:07:04) (c)LFSoft 1997

gotoall: all

# Warning : 'cctype' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
address.o : address.cxx address.hxx ../sharplib/hexa.hxx ../lflib/lfchaine.hxx ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o address.o address.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cassert' can't be located for this node.
config.o : config.cxx sharptool.hxx emul.hxx counters.hxx ../lflib/lfchaine.hxx /usr/include/sys/time.h ../sharplib/libsharp.a \
  Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o config.o config.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cassert' can't be located for this node.
# Warning : 'cstring' can't be located for this node.
CPU.o : CPU.cxx emul.hxx counters.hxx PC-1350.hxx PC-2500.hxx sharptool.hxx address.hxx inst.hxx ../lflib/lfchaine.hxx /usr/include/sys/time.h \
  ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o CPU.o CPU.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cctype' can't be located for this node.
dump.o : dump.cxx sharptool.hxx emul.hxx counters.hxx address.hxx dump.hxx inst.hxx /usr/include/unistd.h ../sharplib/hexa.hxx \
  ../lflib/lfchaine.hxx /usr/include/sys/time.h ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o dump.o dump.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
emul.o : emul.cxx emul.hxx counters.hxx sharptool.hxx address.hxx inst.hxx ../lflib/lfchaine.hxx /usr/include/sys/time.h \
  ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o emul.o emul.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cctype' can't be located for this node.
# Warning : 'climits' can't be located for this node.
exec.o : exec.cxx sharptool.hxx emul.hxx counters.hxx exec.hxx load.hxx address.hxx dump.hxx ../sharplib/hexa.hxx \
  ../sharplib/lectarg.hxx ../lflib/lfchaine.hxx /usr/include/sys/time.h ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o exec.o exec.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cerrno' can't be located for this node.
# Warning : 'climits' can't be located for this node.
# Warning : 'cctype' can't be located for this node.
# Warning : 'csetjmp' can't be located for this node.
# Warning : 'X11/HPkeysym.h' can't be located for this node.
GUI_X.o : GUI_X.cxx sharptool.hxx emul.hxx counters.hxx GUI_X.hxx inst.hxx /usr/include/unistd.h /usr/include/X11/keysym.h \
  /usr/include/Xm/DrawingA.h /usr/include/Xm/ShellEP.h /usr/include/Xm/MainW.h /usr/include/Xm/Xm.h ../lflib/lfchaine.hxx \
  /usr/include/sys/time.h ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o GUI_X.o GUI_X.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
gui_X_1350.o : gui_X_1350.cxx PC-1350.hxx emul.hxx counters.hxx GUI_X.hxx sharptool.hxx /usr/include/X11/keysym.h \
  /usr/include/Xm/DrawingA.h /usr/include/Xm/ShellEP.h /usr/include/Xm/MainW.h /usr/include/Xm/Xm.h ../lflib/lfchaine.hxx \
  /usr/include/sys/time.h ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o gui_X_1350.o gui_X_1350.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
inst.o : inst.cxx dump.hxx inst.hxx emul.hxx counters.hxx ../lflib/lfchaine.hxx /usr/include/sys/time.h ../sharplib/libsharp.a \
  Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o inst.o inst.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cerrno' can't be located for this node.
# Warning : 'climits' can't be located for this node.
load.o : load.cxx sharptool.hxx emul.hxx counters.hxx load.hxx address.hxx ../sharplib/hexa.hxx ../sharplib/lectarg.hxx \
  ../lflib/lfchaine.hxx /usr/include/sys/time.h ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o load.o load.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cerrno' can't be located for this node.
PC-1350.o : PC-1350.cxx PC-1350.hxx emul.hxx counters.hxx sharptool.hxx ../lflib/lfchaine.hxx /usr/include/sys/time.h \
  ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o PC-1350.o PC-1350.cxx 

PC-2500.o : PC-2500.cxx PC-2500.hxx emul.hxx counters.hxx sharptool.hxx ../lflib/lfchaine.hxx /usr/include/sys/time.h \
  ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o PC-2500.o PC-2500.cxx 

gui_X_2500.o : gui_X_2500.cxx PC-2500.hxx emul.hxx counters.hxx GUI_X.hxx sharptool.hxx /usr/include/X11/keysym.h \
  /usr/include/Xm/DrawingA.h /usr/include/Xm/ShellEP.h /usr/include/Xm/MainW.h /usr/include/Xm/Xm.h ../lflib/lfchaine.hxx \
  /usr/include/sys/time.h ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o gui_X_2500.o gui_X_2500.cxx 

# Warning : 'ctime' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdio' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cctype' can't be located for this node.
# Warning : 'climits' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
sharptool.o : sharptool.cxx sharptool.hxx emul.hxx counters.hxx exec.hxx GUI_X.hxx /usr/include/Xm/DrawingA.h \
  /usr/include/Xm/ShellEP.h /usr/include/Xm/MainW.h /usr/include/Xm/Xm.h ../lflib/lfchaine.hxx /usr/include/sys/time.h \
  ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -c -o sharptool.o sharptool.cxx 

../bin/sharptool : sharptool.o PC-1350.o PC-2500.o load.o inst.o gui_X_1350.o gui_X_2500.o GUI_X.o exec.o emul.o dump.o CPU.o config.o address.o \
  ../sharplib/libsharp.a Makefile 
	 g++ -O3 -W -Wall -DDEBUG=1 -I.. -L../sharplib -o ../bin/sharptool sharptool.o PC-1350.o PC-2500.o load.o inst.o gui_X_1350.o gui_X_2500.o \
  GUI_X.o exec.o emul.o dump.o CPU.o config.o address.o -L/usr/X11R6/lib -lsharp -lXm -lXt -lX11 -lrt 

all: ../bin/sharptool 
