# makefile created automaticaly by LFMakeMaker
# LFMakeMaker 2.2 (Mar 26 2000 22:07:04) (c)LFSoft 1997

gotoall: all

../bin/asm : asm.c /usr/include/stdlib.h /usr/include/string.h /usr/include/stdio.h /usr/include/ctype.h Makefile 
	 gcc -O3 -W -Wall -DDEBUG=1 -I../ -o ../bin/asm asm.c 

all: ../bin/asm 
